### ISSUE TITLE
EVM RPC: compatible errors

### ISSUE THREAD

**Issue by kpp** [chainwayxyz/citrea#383]
## Summary

I ran uniswap tests against avail and got a nice error:

1. `anvil --port 12345 --chain-id 5655`
2. `npx hardhat run --network sov scripts/01_deploy.js`

Error is this:

```
    at ......bin/citrea/tests/evm/uniswap/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:265:24
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  reason: 'insufficient funds for intrinsic transaction cost',
  code: 'INSUFFICIENT_FUNDS',
  error: ProviderError: Insufficient funds for gas * price + value
  ```

However when I ran hardhat tests against our node and got this error from sequencer:

```
2024-04-15T12:06:36.336554Z TRACE method_call{method="eth_sendRawTransaction"}: jsonrpsee_core::tracing: send="{\"jsonrpc\":\"2.0\",\"error\":{\"code\":-32003,\"message\":\"ETH_RPC_ERROR\",\"data\":\"[0x85b0ac98e84e898a5778488d1f95d617fad90b5f599ffafeadd4b15004d1c75d]: insufficient gas price to replace existing transaction\"},\"id\":19}"
```

And in hardhat the error looks like this:

```
ProviderError: ETH_RPC_ERROR
    at HttpProvider.request (......bin/citrea/tests/evm/uniswap/node_modules/hardhat/src/internal/core/providers/http.ts:88:21)
```

So our RPC errors are not properly recognized by hardhat/ethers. We need to fix it.

**Comment by eyusufatik** [comment]
looks like we send the same `ETH_RPC_ERROR` message for everything

let's check out how other eth clients send error responses.

there might be differences from client to client, we can imitate geth or reth
