### ISSUE TITLE
Sequencer substraction overflow

### ISSUE THREAD

**Issue by eyusufatik** [chainwayxyz/citrea#932]
## Summary

Somehow block production took more than 2 seconds, and then, from my understanding the sequencer failed on these lines:

```rust
let mut interval = tokio::time::interval(target_block_time - parent_block_exec_time);
// The first ticket completes immediately.
// See: https://docs.rs/tokio/latest/tokio/time/struct.Interval.html#method.tick
interval.tick().await;
```

```sh
2024-07-30T14:45:00.251761Z ERROR Sequencer: panic: thread 'main' panicked at 'overflow when subtracting durations': /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/time.rs:1126
   0: <backtrace::capture::Backtrace as core::default::Default>::default
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/backtrace-0.3.73/src/capture.rs:422:9
   1: log_panics::Config::install_panic_hook::{{closure}}
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/log-panics-2.1.0/src/lib.rs:115:29
   2: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/alloc/src/boxed.rs:2034:9
      std::panicking::rust_panic_with_hook
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:783:13
   3: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:657:13
   4: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/sys_common/backtrace.rs:171:18
   5: rust_begin_unwind
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:645:5
   6: core::panicking::panic_fmt
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panicking.rs:72:14
   7: core::panicking::panic_display
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panicking.rs:197:5
   8: core::panicking::panic_str
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/panicking.rs:172:5
      core::option::expect_failed
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/option.rs:1995:5
   9: core::option::Option<T>::expect
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/option.rs:896:21
      <core::time::Duration as core::ops::arith::Sub>::sub
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/time.rs:1126:31
  10: citrea_sequencer::sequencer::CitreaSequencer<C,Da,Sm,Vm,Stf>::run::{{closure}}::{{closure}}::{{closure}}
             at /root/citrea/crates/sequencer/src/sequencer.rs:856:54
  11: citrea_sequencer::sequencer::CitreaSequencer<C,Da,Sm,Vm,Stf>::run::{{closure}}::{{closure}}
             at /root/citrea/crates/sequencer/src/sequencer.rs:774:5
  12: citrea_sequencer::sequencer::CitreaSequencer<C,Da,Sm,Vm,Stf>::run::{{closure}}
             at /root/citrea/crates/sequencer/src/sequencer.rs:774:5
  13: citrea_sequencer::Sequencer<S>::run_and_report_rpc_port::{{closure}}
             at /root/citrea/crates/sequencer/src/lib.rs:57:19
  14: citrea_sequencer::Sequencer<S>::run::{{closure}}::{{closure}}::{{closure}}
             at /root/citrea/crates/sequencer/src/lib.rs:44:44
  15: citrea_sequencer::Sequencer<S>::run::{{closure}}::{{closure}}
             at /root/citrea/crates/sequencer/src/lib.rs:36:5
  16: <tracing::instrument::Instrumented<T> as core::future::future::Future>::poll
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-0.1.40/src/instrument.rs:321:9
  17: citrea_sequencer::Sequencer<S>::run::{{closure}}
             at /root/citrea/crates/sequencer/src/lib.rs:36:5
  18: citrea::start_rollup::{{closure}}::{{closure}}::{{closure}}
             at /root/citrea/bin/citrea/src/main.rs:148:48
  19: citrea::start_rollup::{{closure}}::{{closure}}
             at /root/citrea/bin/citrea/src/main.rs:123:1
  20: citrea::start_rollup::{{closure}}
             at /root/citrea/bin/citrea/src/main.rs:123:1
  21: citrea::main::{{closure}}
             at /root/citrea/bin/citrea/src/main.rs:107:14
  22: tokio::runtime::park::CachedParkThread::block_on::{{closure}}
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/park.rs:281:63
  23: tokio::runtime::coop::with_budget
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/coop.rs:107:5
      tokio::runtime::coop::budget
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/coop.rs:73:5
      tokio::runtime::park::CachedParkThread::block_on
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/park.rs:281:31
  24: tokio::runtime::context::blocking::BlockingRegionGuard::block_on
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/context/blocking.rs:66:9
  25: tokio::runtime::scheduler::multi_thread::MultiThread::block_on::{{closure}}
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/scheduler/multi_thread/mod.rs:87:13
  26: tokio::runtime::context::runtime::enter_runtime
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/context/runtime.rs:65:16
  27: tokio::runtime::scheduler::multi_thread::MultiThread::block_on
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/scheduler/multi_thread/mod.rs:86:9
  28: tokio::runtime::runtime::Runtime::block_on
             at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tokio-1.38.0/src/runtime/runtime.rs:349:45
  29: citrea::main
             at /root/citrea/bin/citrea/src/main.rs:93:5
  30: core::ops::function::FnOnce::call_once
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/ops/function.rs:250:5
  31: std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/sys_common/backtrace.rs:155:18
  32: std::rt::lang_start::{{closure}}
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/rt.rs:166:18
  33: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/core/src/ops/function.rs:284:13
      std::panicking::try::do_call
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:552:40
      std::panicking::try
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:516:19
      std::panic::catch_unwind
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panic.rs:146:14
      std::rt::lang_start_internal::{{closure}}
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/rt.rs:148:48
      std::panicking::try::do_call
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:552:40
      std::panicking::try
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panicking.rs:516:19
      std::panic::catch_unwind
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/panic.rs:146:14
      std::rt::lang_start_internal
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/rt.rs:148:20
  34: std::rt::lang_start
             at /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/rt.rs:165:17
  35: main
  36: __libc_start_call_main
             at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  37: __libc_start_main_impl
             at ./csu/../csu/libc-start.c:360:3
  38: _start
  ```

**Comment by yaziciahmet** [comment]
Had the same issue but reproduced it differently. Ran sequencer and a prover with bitcoin-regtest as DA. Spammed L1 blocks to bitcoin. Prover errored with this error.

**Comment by yaziciahmet** [comment]
It seems error seems to be happening in the following code piece:
```rs
            let first_l2_height_of_l1 = sequencer_commitments[0].l2_start_block_number;
            let last_l2_height_of_l1 =
                sequencer_commitments[sequencer_commitments.len() - 1].l2_end_block_number;

            // If the L2 range does not exist, we break off the local loop getting back to
            // the outer loop / select to make room for other tasks to run.
            // We retry the L1 block there as well.
            if !self.check_l2_range_exists(first_l2_height_of_l1, last_l2_height_of_l1) {
                break;
            }
```
When I logged first and last l2's it was 401 and 100 respectively. My guess is that extract_sequencer_commitments method returns commitments unordered. Didn't confirm this for sure, leaving this as a hint.

**Comment by rakanalh** [comment]
@yaziciahmet please create a separate issue for what you've described since it's unrelated to what Esad is describing.
